---

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.2
  
  Exclude:
    - spec/rails/**/*
    - gemfiles/vendor/bundle/**/*

  Include:
    - "**/*.rake"
    - "**/Gemfile"
    - "**/Rakefile"

  DisplayCopNames: true

  StyleGuideCopsOnly: false
